### ISSUE TITLE
Database Required

### ISSUE THREAD

**Issue by mfa237** [abdulmanan7/stms#1]
Dear Sir,
Kindly provide the database of this project. I will be very thankful to you...

**Comment by abdulmanan7** [comment]
sorry this is not open source ! also it has been made for pakistan tailor community

**Comment by mfa237** [comment]
kindly tell me the price?

**Comment by abdulmanan7** [comment]
Its a $300 having 1 week free support if you want maintanance $50/m

**Comment by mfa237** [comment]
ok thanks
